name: Xcode

on: [push]

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Add certificate
      run: |
        # keychain setup
        security create-keychain -p password build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p password build.keychain
        
        # certificate setup
        # echo ${{ secrets.CERTIFICATE_DISTRIBUTION_P12_BASE64 }} | base64 --decode > $HOME/ios_distribution.p12
        # echo ${{ secrets.CERTIFICATE_DISTRIBUTION_BASE64 }} | base64 --decode > $HOME/ios_distribution.cer
        # security import $HOME/ios_distribution.cer -T /usr/bin/codesign
        # security import $HOME/ios_distribution.p12 -T /usr/bin/codesign -P ""
        
        echo ${{ secrets.CERTIFICATE_BASE64 }} | base64 --decode > $HOME/certificate.p12
        security import $HOME/certificate.p12 -T /usr/bin/codesign -P ""
        
        # keychain setup
        security set-key-partition-list -S apple-tool:,apple: -s -k password build.keychain
    - name: Add Provisioning Profile
      run: |
        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        echo ${{ secrets.PROVISIONING_PROFILE_DISTRIBUTION_BASE64 }} | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/development.mobileprovision"
    - name: Archive
      run: |
        xcodebuild -configuration Release -scheme ghactions-test -project ghactions-test.xcodeproj -archivePath ghactions-test.xcarchive archive
    - name: Export
      run: xcodebuild -exportArchive -archivePath ghactions-test.xcarchive -exportPath ghactions-test.ipa -exportOptionsPlist ExportOptions.plist
    - name: Upload
      run: |
        ls -al
        xcrun altool --upload-app -f ghactions-test.ipa/ghactions-test.ipa -t ios -u akimonoiryou@me.com -p ${{ secrets.APPLE_API_KEY }}
