name: Xcode

on: [push]

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1

    - name: ruby
      run: sudo gem install jwt

    - name: access api
      run: |
        curl -v -H 'Authorization: Bearer '$(ruby jwt.rb "$(echo ${{ secrets.AUTH_KEY_BASE64 }})") https://api.appstoreconnect.apple.com/v1/apps

    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.1.app/Contents/Developer'
    - name: Setup keychain
      run: |
        security create-keychain -p password build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p password build.keychain
    - name: Add certificate
      run: |
        echo ${{ secrets.CERTIFICATE_BASE64 }} | base64 --decode > $HOME/certificate.p12
        security import $HOME/certificate.p12 -T /usr/bin/codesign -P ""
    - name: Allow apple tools to access keychain
      run: |
        security set-key-partition-list -S apple-tool:,apple: -s -k password build.keychain
    - name: Add Provisioning Profile
      run: |
        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        echo ${{ secrets.PROVISIONING_PROFILE_BASE64 }} | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/development.mobileprovision"
    - name: Archive
      run: xcodebuild -configuration Release -scheme ghactions-test -project ghactions-test.xcodeproj -archivePath ghactions-test.xcarchive archive
    - name: Export
      run: xcodebuild -exportArchive -archivePath ghactions-test.xcarchive -exportPath ghactions-test.ipa -exportOptionsPlist ExportOptions.plist
    - name: Upload
      run: xcrun altool --upload-app -f ghactions-test.ipa/ghactions-test.ipa -t ios -u ${{ secrets.APPLE_USER }} -p ${{ secrets.APPLE_API_KEY }}
