name: Xcode

on: [push]

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: add cert
      run: |
        security create-keychain -p password build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p password build.keychain
        echo ${{ secrets.IOS_DEVELOPMENT_CERT_BASE64 }} | base64 --decode > $HOME/ios_development.cert
        security add-certificate $HOME/ios_development.cert
    - name: cert
      run: |
        security default-keychain
        security find-certificate
    - name: Add Provisioning Profile
      run: |
        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        echo ${{ secrets.PROVISIONING_PROFILE_APPSTORE_BASE64 }} | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/distribution.mobileprovision"
        echo ${{ secrets.PROVISIONING_PROFILE_DEVELOPMENT_BASE64 }} | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/development.mobileprovision"
        echo ${{ secrets.PROVISIONING_PROFILE_BASE64 }} | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/development.mobileprovision"
    - name: Archive
      run: xcodebuild -configuration Release -scheme ghactions-test -project ghactions-test.xcodeproj -archivePath ghactions-test.xcarchive archive
